name: twitter_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependency for managing states in the app
  provider: ^6.1.3

  # Dependency for animations like the like button
  lottie: ^2.4.0

  # Dependency for icons (e.g., material design, social icons)
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.5.0

  # Appwrite SDK for backend API integration
  appwrite: ^12.0.4

  # HTTP requests (for API calls if needed)
  http: ^0.15.0

  # Flutter toast messages (e.g., for task success or error notifications)
  fluttertoast: ^8.2.1

  # Dependency for beautiful UI components
  flutter_staggered_grid_view: ^0.6.2

    # Modern styling for buttons, forms, and input fields
  flutter_neumorphic: ^3.3.0
  google_fonts: ^4.0.4

  # Advanced animations for buttons and transitions
  animations: ^2.0.5
  lottie: ^2.4.0

  # User input and forms
  form_validator: ^1.1.0

  # State management
  provider: ^6.1.3

  # Smooth page transitions for multi-screen flows
  smooth_page_indicator: ^1.0.0

  # Dependency for form validation (e.g., profile editing)
  form_validator: ^1.1.0

  # Dependency for search bar and filtering
  search_choices: ^2.1.3

  # Dependency for custom drawer and navigation
  flutter_drawer: ^0.0.2

  # For rich text and hashtags display
  flutter_mentions: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Adding assets
  assets:
    - assets/icons/
    - assets/animations/

  # Adding fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
